# Mengubah port ke 8081 agar tidak bertabrakan dengan program lain
server.port=8081

# 1. Driver MySQL versi baru menggunakan .cj.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. URL Database (Tambahkan zona waktu untuk mencegah error koneksi di MySQL modern)
# spring.datasource.url=jdbc:mysql://133.186.145.150:11230/blog?serverTimezone=UTC
# spring.datasource.username=test
# spring.datasource.password=testAdvis!23

spring.datasource.url=jdbc:mysql://localhost:3306/blog?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# 3. BARIS INI WAJIB DIHAPUS. Properti lama ini menyebabkan crash di Hibernate 6 (Spring Boot 3)
# spring.jpa.properties.hibernate.id.new_generator_mappings=false